// ─── Mobile S styles object ──────────────────────────────────export
export const S ={
  page: {
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    background: "#f0f2f7",
    minHeight: "100vh",
    paddingBottom: "100px",
    boxSizing: "border-box",
    overflowX: "hidden",
    width: "100%",
  },
  headerBar: {
    background: "#0f172a",
    padding: "16px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    zIndex: 100,
    boxShadow: "0 2px 12px rgba(0,0,0,0.25)",
  },
  headerLeft: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  headerTitle: {
    color: "#fff",
    fontSize: "1.05rem",
    fontWeight: 800,
    margin: 0,
    letterSpacing: "-0.01em",
  },
  headerHint: {
    color: "#94a3b8",
    fontSize: "0.72rem",
    fontWeight: 500,
  },
  shopBadge: (color) => ({
    background: color + "22",
    color: color,
    border: `1.5px solid ${color}55`,
    padding: "5px 12px",
    borderRadius: "100px",
    fontSize: "0.72rem",
    fontWeight: 700,
    whiteSpace: "nowrap",
    flexShrink: 0,
  }),
  tabBar: {
    display: "flex",
    background: "#fff",
    borderBottom: "1.5px solid #e8eaf0",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  tabBtn: (active) => ({
    flex: 1,
    padding: "13px 8px",
    border: "none",
    background: "none",
    fontSize: "13px",
    fontWeight: active ? 800 : 600,
    color: active ? "#0f172a" : "#94a3b8",
    borderBottom: active ? "2.5px solid #0f172a" : "2.5px solid transparent",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 0.18s",
  }),
  body: {
    padding: "14px 14px 0",
  },
  // ── Stats row ─────────────────────────────────────────────
  statsRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    marginBottom: "14px",
  },
  statCard: (color) => ({
    background: "#fff",
    borderRadius: "14px",
    padding: "14px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
    borderLeft: `4px solid ${color}`,
  }),
  statLabel: {
    fontSize: "0.68rem",
    color: "#64748b",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.03em",
    marginBottom: "5px",
  },
  statValue: {
    fontSize: "1.25rem",
    fontWeight: 900,
    color: "#0f172a",
  },
  // ── Warning / info banners ─────────────────────────────────
  warnBanner: {
    background: "#fffbeb",
    border: "1px solid #fcd34d",
    borderRadius: "12px",
    padding: "11px 14px",
    marginBottom: "12px",
    fontSize: "0.8rem",
    color: "#92400e",
  },
  lowStockBanner: {
    background: "#fff7ed",
    border: "1px solid #fed7aa",
    borderRadius: "12px",
    padding: "12px 14px",
    marginBottom: "12px",
  },
  lowStockTitle: {
    color: "#c2410c",
    fontSize: "0.83rem",
    fontWeight: 700,
    marginBottom: "8px",
  },
  lowStockChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  lowStockChip: {
    background: "#fee2e2",
    color: "#991b1b",
    padding: "3px 10px",
    borderRadius: "100px",
    fontSize: "0.7rem",
    fontWeight: 700,
  },
  // ── Form card ──────────────────────────────────────────────
  formCard: {
    background: "#fff",
    borderRadius: "16px",
    padding: "16px",
    marginBottom: "12px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.06)",
  },
  sectionDivider: (color) => ({
    fontSize: "0.68rem",
    fontWeight: 800,
    color: color,
    textTransform: "uppercase",
    letterSpacing: "0.07em",
    marginBottom: "12px",
    paddingBottom: "8px",
    borderBottom: `2px solid ${color}22`,
  }),
  fieldGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
  },
  fieldFull: {
    gridColumn: "1 / -1",
  },
  fieldLabel: {
    fontSize: "0.68rem",
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: "5px",
    display: "block",
  },
  mInput: {
    width: "100%",
    padding: "11px 13px",
    borderRadius: "10px",
    border: "1.5px solid #e2e8f0",
    fontSize: "14px",
    background: "#f8fafc",
    outline: "none",
    boxSizing: "border-box",
    color: "#0f172a",
    transition: "border-color 0.15s",
    WebkitAppearance: "none",
  },
  mSelect: {
    width: "100%",
    padding: "11px 13px",
    borderRadius: "10px",
    border: "1.5px solid #e2e8f0",
    fontSize: "14px",
    background: "#f8fafc",
    outline: "none",
    boxSizing: "border-box",
    color: "#0f172a",
    cursor: "pointer",
    WebkitAppearance: "none",
  },
  // ── Margin preview ─────────────────────────────────────────
  marginPreview: {
    background: "#f8fafc",
    borderRadius: "12px",
    padding: "12px 14px",
    marginTop: "10px",
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  marginLabel: {
    fontSize: "0.8rem",
    color: "#64748b",
  },
  // ── GST Preview box ────────────────────────────────────────
  gstPreview: {
    background: "#f0fdf4",
    border: "1px solid #bbf7d0",
    borderRadius: "12px",
    padding: "12px 14px",
    marginTop: "10px",
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  gstPreviewLabel: {
    fontSize: "0.8rem",
    color: "#15803d",
  },
  // ── Gold GST preview box ───────────────────────────────────
  goldGstPreview: {
    background: "#fffbeb",
    border: "1px solid #fde68a",
    borderRadius: "12px",
    padding: "12px 14px",
    marginTop: "10px",
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
    fontSize: "0.8rem",
    color: "#78350f",
  },
  // ── Action buttons ─────────────────────────────────────────
  actionRow: {
    display: "flex",
    gap: "10px",
    marginTop: "14px",
  },
  saveBtn: (color) => ({
    flex: 1,
    padding: "14px",
    borderRadius: "12px",
    border: "none",
    background: color,
    color: "#fff",
    fontWeight: 800,
    fontSize: "0.95rem",
    cursor: "pointer",
    boxShadow: `0 4px 14px ${color}44`,
  }),
  cancelBtn: {
    padding: "14px 18px",
    borderRadius: "12px",
    border: "1.5px solid #e2e8f0",
    background: "#fff",
    color: "#64748b",
    fontWeight: 700,
    fontSize: "0.9rem",
    cursor: "pointer",
  },
  // ── Search & filter ─────────────────────────────────────────
  searchWrap: {
    display: "flex",
    gap: "10px",
    marginBottom: "12px",
  },
  searchInput: {
    flex: 1,
    padding: "11px 14px",
    borderRadius: "10px",
    border: "1.5px solid #e2e8f0",
    fontSize: "14px",
    background: "#fff",
    outline: "none",
    color: "#0f172a",
  },
  filterSelect: {
    padding: "11px 12px",
    borderRadius: "10px",
    border: "1.5px solid #e2e8f0",
    fontSize: "13px",
    background: "#fff",
    outline: "none",
    color: "#0f172a",
    cursor: "pointer",
    WebkitAppearance: "none",
    minWidth: "110px",
  },
  listCount: {
    fontSize: "0.8rem",
    color: "#64748b",
    fontWeight: 700,
    marginBottom: "10px",
  },
  // ── Stock item card ─────────────────────────────────────────
  stockCard: {
    background: "#fff",
    borderRadius: "14px",
    padding: "14px",
    marginBottom: "10px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
    border: "1.5px solid #f0f2f7",
  },
  stockCardTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: "8px",
    gap: "8px",
  },
  stockName: {
    fontSize: "0.95rem",
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1.3,
  },
  badgeRow: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
    marginTop: "4px",
  },
  lowBadge: {
    background: "#fee2e2",
    color: "#991b1b",
    fontSize: "0.6rem",
    fontWeight: 700,
    padding: "2px 8px",
    borderRadius: "100px",
    textTransform: "uppercase",
  },
  expiryBadge: {
    background: "#fef3c7",
    color: "#92400e",
    fontSize: "0.6rem",
    fontWeight: 700,
    padding: "2px 8px",
    borderRadius: "100px",
  },
  stockMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    marginBottom: "10px",
  },
  metaChip: {
    fontSize: "0.75rem",
    color: "#64748b",
    background: "#f8fafc",
    padding: "3px 10px",
    borderRadius: "100px",
    fontWeight: 600,
  },
  stockActions: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  editBtn: (color) => ({
    padding: "7px 16px",
    borderRadius: "8px",
    background: color,
    color: "#fff",
    border: "none",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
  }),
  removeBtn: {
    padding: "7px 14px",
    borderRadius: "8px",
    background: "#fee2e2",
    color: "#dc2626",
    border: "none",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  confirmRow: {
    display: "flex",
    gap: "6px",
  },
  confirmYes: {
    padding: "7px 12px",
    borderRadius: "8px",
    background: "#dc2626",
    color: "#fff",
    border: "none",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  confirmNo: {
    padding: "7px 10px",
    borderRadius: "8px",
    background: "#f1f5f9",
    color: "#64748b",
    border: "none",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  // ── Expiry warning ──────────────────────────────────────────
  expiryWarning: {
    background: "#fef3c7",
    border: "1px solid #fcd34d",
    borderRadius: "10px",
    padding: "10px 14px",
    fontSize: "0.78rem",
    color: "#92400e",
    gridColumn: "1 / -1",
    marginTop: "4px",
  },
  // ── Gold total box ──────────────────────────────────────────
  goldTotal: {
    background: "#fef9c3",
    border: "1px solid #fde68a",
    borderRadius: "10px",
    padding: "12px 14px",
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
    fontSize: "0.8rem",
    color: "#78350f",
    gridColumn: "1 / -1",
    marginTop: "4px",
  },
  // ── Toast ───────────────────────────────────────────────────
  toast: (type) => ({
    position: "fixed",
    top: "72px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 9999,
    padding: "10px 24px",
    borderRadius: "100px",
    fontWeight: 600,
    fontSize: "0.85rem",
    whiteSpace: "nowrap",
    background: type === "success" ? "#0e1b2e" : "#dc2626",
    color: "#fff",
    boxShadow: "0 4px 20px rgba(0,0,0,0.18)",
  }),
  emptyBox: {
    background: "#fff",
    borderRadius: "14px",
    padding: "40px 20px",
    textAlign: "center",
    color: "#94a3b8",
    fontSize: "0.9rem",
    fontWeight: 600,
    border: "1.5px dashed #e2e8f0",
  },
};